server:
    port: 5000 # The port on which the server will be running.
    websocket_support: true # Enable WebSocket protocol support. If set to true, the server will support WebSocket connections.

settings:
    max_threads: 30000 # The maximum number of request handlers that can be concurrently running. Increasing this value allows the server to handle more requests simultaneously.
    max_data: 10 # The maximum size of data in the request body, in megabytes. If a request contains data exceeding this size, the server may reject the request.
    check_updates: true # Enable server update checking from the git repository. When enabled, the server will periodically check for updates and prompt for an update if available.

garbage:
    enabled: false # Enable automatic garbage collection. When enabled, the server will periodically clean up unused resources to optimize memory usage.
    interval: 0 # The interval in minutes between automatic garbage collection invocations. The default value is set to 5 minutes.

# Authentication parameters
auth:
    login: root
    password: root
